services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config_ha:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    restart: unless-stopped
    shm_size: "128mb"
    depends_on:
      - mosquitto
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # Tu aceleración gráfica Intel/AMD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config_frigate:/config 
      - ./frigate_media:/media/frigate
      # Escudo protector para SSD usando 1GB de RAM para la caché
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971" # Interfaz Web Segura (Pide login)
      - "5000:5000" # Interfaz Web Clásica
      - "1984:1984" # Interfaz de go2rtc
      - "8554:8554" # RTSP Restream
      - "8555:8555/tcp"
      - "8555:8555/udp"
    environment:
      - TZ=Europe/Madrid
      - FRIGATE_RTSP_USER=${FRIGATE_RTSP_USER}
      - FRIGATE_RTSP_PASSWORD=${FRIGATE_RTSP_PASSWORD}
      - FRIGATE_CAM_IP=${FRIGATE_CAM_IP}
    networks:
      - red-home-lab
  
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./config_mosquitto:/mosquitto/config
      - ./mosquitto_data:/mosquitto/data
    networks:
      - red-home-lab

networks:
  red-home-lab:
    external: true