services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/babs-dev18/infraestructura/domotica/config_ha:/config
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - "8123"
    restart: unless-stopped
    privileged: true
    network_mode: host

  # go2rtc.yaml
  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    privileged: true
    network_mode: host
    restart: unless-stopped
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    volumes:
      - ./go2rtc.yaml:/config/go2rtc.yaml
      
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    privileged: true
    restart: unless-stopped
    shm_size: "128mb"
    depends_on:
      - go2rtc # Espera a que go2rtc esté levantado antes de arrancar
      - mosquitto # 🦟 Asegura que Mosquitto esté vivo antes de que Frigate intente loguearse
    devices:
      # /dev/video0 ELIMINADO de aquí de forma definitiva para evitar congelar el kernel
      - /dev/dri/renderD128:/dev/dri/renderD128 # Aceleración por hardware de Intel/AMD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/babs-dev18/infraestructura/domotica/config_frigate:/config
      # CLIPS Y SNAPSHOTS Cambio al nmve para probar
      - ./frigate_media:/media/frigate
    ports:
      - "5000:5000" # Web de Frigate
      # - "1984:1984" # 🚀 Web del go2rtc INCLUIDO dentro de Frigate
      # - "8554:8554" # RTSP de go2rtc incluido en Frigate
      - "8555:8555/tcp" # WebRTC
      - "8555:8555/udp" # WebRTC
    environment:
      - TZ=${TZ}
    networks:
      - red-home-lab # Le decimos a Frigate que use la red común

  compreface:
    container_name: compreface
    image: exadel/compreface:1.2.0
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TZ=${TZ}
    networks:
      - red-home-lab # Enganchamos CompreFace a la red común

  double-take:
    container_name: double-take
    image: jakowenko/double-take:latest
    restart: unless-stopped
    ports:
      - "3300:3300"
    volumes:
      - ./double-take:/storage
    environment:
      - TZ=${TZ}
    networks:
      - red-home-lab #  Enganchamos Double Take a la red común

  
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./config_mosquitto:/mosquitto/config
      - ./mosquitto_data:/mosquitto/data
    networks:
      - red-home-lab


# 🌐 Definimos las redes al final del archivo
networks:
  red-home-lab:
    external: true
