# Frigate config.yml

mqtt:
  host: mosquitto # El nombre del contenedor en la red común
  port: 1883
  enabled: true # Imprescindible para hablar con Double Take y Home Assistant

# 🧠 Aceleración por Hardware usando Intel OpenVINO
detectors:
  cpu_detector:
    type: cpu # Cambiado de openvino a cpu puro

# 🎯 Definición de los objetos que la IA debe rastrear globalmente
objects:
  track:
    - cat # Le decimos a la IA que solo busque gatos

# 📹 Configuración de las cámaras
cameras:
  loocam_analoga: # El nombre que le damos a la cámara analógica
    ffmpeg:
      inputs:
        - path: rtsp://go2rtc:8554/loocam_analoga
          roles:
            - detect # Este flujo se usa para que la IA analice el movimiento
            - record # Este flujo se usa para guardar los clips de vídeo

      # SIN ACELERACIÓN: No se toca la gráfica para no perjudicar a Jellyfin
      input_args: -avoid_negative_ts make_zero -an
      hwaccel_args: []
    # 📉 Ajuste de resolución y FPS para optimizar tu CPU
    detect:
      width: 640
      height: 480
      fps: 4

    # 💾 Configuración de grabaciones (para cuando la IA detecte al gato)
    # Frigate v0.13
    record:
      enabled: true
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
      continuous:
        days: 0
      motion:
        days: 0

# Frigate v0.14+     
#  record:
#   enabled: true
#   retain:
#     days: 3 # Guarda las grabaciones normales durante 3 días
#     mode: all
#   events:
#     retain:
#       default: 14 # Guarda los clips donde sale un gato durante 14 días
#       mode: active_objects
#

        
    # 📸 Necesitamos capturar fotos cuando aparezca el gato para mandárselas a la IA facial      
    snapshots:
      enabled: true
      draw_bounding_box: false
      bounding_box: false
      retain:
        default: 7 # Guarda las fotos de los eventos 7 días

    # 🗺️ Definición de la Zona del arenero
    zones:
      zona_arenero:
        coordinates: 0.1,0.1,0.9,0.1,0.9,0.9,0.1,0.9 # Coordenadas de ejemplo (luego las ajustaremos con su interfaz visual)