mqtt:
  host: mosquitto
  port: 1883
  enabled: true

detectors:
  ov:
    type: openvino
    device: CPU

go2rtc:
  streams:
    tapo_michi18:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_CAM_IP}:554/stream1#backchannel=0#transport=tcp
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_CAM_IP}:554/stream2#backchannel=0#transport=tcp

objects:
  track:
    - cat

cameras:
  tapo_michi18:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tapo_michi18?video=2
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/tapo_michi18?video=1
          roles:
            - record
      input_args: -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
      hwaccel_args: []

    detect:
      width: 1280
      height: 720
      fps: 5

    onvif:
      host: "{FRIGATE_CAM_IP}"
      port: 2020
      user: "{FRIGATE_RTSP_USER}"
      password: "{FRIGATE_RTSP_PASSWORD}"

    record:
      enabled: true
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 14
          mode: active_objects

    snapshots:
      enabled: true
      retain:
        default: 7

    zones:
      zona_arenero:
        coordinates: 0.1,0.1,0.9,0.1,0.9,0.9,0.1,0.9