mqtt:
  host: mosquitto
  port: 1883
  enabled: true

detectors:
  ov:
    type: openvino
    device: CPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  streams:
    tapo_michi18:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.25:554/stream1
      - ffmpeg:tapo_michi18#audio=aac

objects:
  track:
    - cat

cameras:
  tapo_michi18:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tapo_michi18
          input_args: preset-rtsp-restream # Prepara a FFmpeg para leer desde go2rtc
          roles:
            - detect
            - record
            - audio

    detect:
      width: 1280
      height: 720
      fps: 5

    audio:
      enabled: false # Go2rtc ya lo gestiona arriba

    onvif:
      host: 192.168.1.25
      port: 2020
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'

    record:
      enabled: true
      continuous:
        days: 3
      alerts:
        retain:
          days: 14
      detections:
        retain:
          days: 14
      motion:
        days: 0

    snapshots:
      enabled: true
      retain:
        default: 7

    zones:
      zona_arenero:
        coordinates: 0.333,0.163,0.631,0.285,0.624,0.873,0.305,0.877

        inertia: 3
        loitering_time: 10
        objects: 
          - cat
    review:
      alerts:
        required_zones: zona_arenero
version: 0.17-0