mqtt:
  host: mosquitto
  port: 1883
  enabled: true

detectors:
  ov:
    type: openvino
    device: CPU

go2rtc:
  streams:
    tapo_michi18:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_CAM_IP}:554/stream1
    tapo_michi18_low:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@{FRIGATE_CAM_IP}:554/stream2

objects:
  track:
    - cat

cameras:
  tapo_michi18:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tapo_michi18_low
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/tapo_michi18
          roles:
            - record
            - audio
  
    detect:
      width: 1280
      height: 720
      fps: 5

    audio:
      enabled: true

#    onvif:
#      host: "{FRIGATE_CAM_IP}"
#      port: 2020
#      user: "{FRIGATE_RTSP_USER}"
#      password: "{FRIGATE_RTSP_PASSWORD}"
#
    record:
      enabled: true
      continuous:
        days: 3 # Graba 24/7 de forma continua durante 3 días
      alerts:
        retain:
          days: 14 # Guarda eventos importantes (gatos en el arenero) durante 14 días
      detections:
        retain:
          days: 14 # Guarda detecciones normales durante 14 días
      motion:
        days: 0

    snapshots:
      enabled: true
      retain:
        default: 7

    zones:
      zona_arenero:
        coordinates: 0.1,0.1,0.9,0.1,0.9,0.9,0.1,0.9

version: 0.17-0