# double-take yml

# 🌐 Configuración general del sistema
server:
  ports: 3300

# 🐈 Conexión nativa con el motor de vídeo (Frigate)
frigate:
  url: http://frigate:5000 # Al estar en la misma red de Docker, usamos el nombre del contenedor

# 🧠 Conexión con el motor de reconocimiento (CompreFace)
detect:
  compreface:
    url: http://compreface:8000
    # Usamos la clave de API que definiremos en nuestro archivo seguro .env
    key: ${COMPREFACE_API_KEY} 

# 🎯 Configuración del flujo de análisis
frigate:
  attempts: { amped: 5 } # Intentos máximos de captura por evento para no saturar la CPU
  cameras:
    - loocam_analoga # Debe coincidir exactamente con el nombre que pusimos en Frigate
  zones:
    - name: zona_arenero # Solo analiza si el gato está dentro de la zona que nos interesa
  objects:
    - cat 