# double-take yml

# 🌐 Configuración general del sistema
server:
  ports: 3300



# 🧠 Conexión con el motor de reconocimiento (CompreFace)
plugins:
  compreface:
    url: http://compreface:8000
    key: ${COMPREFACE_API_KEY}


# 🐈 Conexión nativa con el motor de vídeo (Frigate)
frigate:
  url: http://frigate:5000 # Nombre del contenedor en la red común
  attempts:
    default: 5 # Intentos de captura por evento
  cameras:
    - loocam_analoga 
  zones:
    - name: zona_arenero 
  objects:
    - cat